// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BehavioursDocumentationGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class BehaviourPage : BehaviourPageBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"
<html>
	<head>
		<meta http-equiv=""Content-Type"" content=""text/html; charset=utf-8"" />
		<link href=""css/bootstrap.min.css"" rel=""stylesheet"">
	</head>
	<body>
		<div class=""navbar navbar-default navbar-fixed-top"" role=""navigation"">
			<div class=""container"">
				<div class=""navbar-header"">
					<button type=""button"" class=""navbar-toggle"" data-toggle=""collapse"" data-target="".navbar-collapse"">
						<span class=""sr-only"">Toggle navigation</span>
						<span class=""icon-bar""></span>
						<span class=""icon-bar""></span>
						<span class=""icon-bar""></span>
					</button>
					<a class=""navbar-brand"" href=""#"">");
            
            #line 22 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(@"</a>
				</div>
				<div class=""navbar-collapse collapse"">
					<ul class=""nav navbar-nav navbar-right"">
					<li><a href=""index.html"">На главную</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class=""container"">
			<div class=""page-header"">
				<h1>&nbsp;</h1>
				<p class=""lead"">");
            
            #line 34 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Description));
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t</div>\r\n\r\n\t\t\t<h2><span class=\"label label-default\">Состояния</span></h2>" +
                    "\r\n\t\t\t");
            
            #line 38 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
foreach (var state in Model.States){
            
            #line default
            #line hidden
            this.Write("\t\t\t<h3>");
            
            #line 39 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.Name));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t<p>");
            
            #line 40 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.Description));
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t");
            
            #line 41 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t<h2><span class=\"label label-default\">Действия</span></h2>\r\n\t\t\t");
            
            #line 44 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
foreach (var action in Model.Actions){
            
            #line default
            #line hidden
            this.Write("\t\t\t<h3>");
            
            #line 45 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t<p>");
            
            #line 46 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Description));
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t");
            
            #line 47 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t<h2><span class=\"label label-default\">События</span></h2>\r\n\t\t\t");
            
            #line 50 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
foreach (var gameEvent in Model.Events){
            
            #line default
            #line hidden
            this.Write("\t\t\t<h3>");
            
            #line 51 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gameEvent.Name));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t<p>");
            
            #line 52 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gameEvent.Description));
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t");
            
            #line 53 "D:\creative\shine12\HEAD\BehavioursDocumentationGenerator\Templates\BehaviourPage.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t</div>\r\n\t</body>\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class BehaviourPageBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
